languageCode = "en-us"
title = "Serverless Academy Blog"
baseURL = "https://linuxacademy.github.io/serverless-blog/"
theme = "slsa_theme_blog"

[params]
  dateformat = "Mon, Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Source+Code+Pro|Source+Sans+Pro:400,700" # Optional, Include google fonts.
  fontfamily = "'Source Sans Pro',sans-serif" # Optional, Override body font family.
  logofontfamily = "'Source Code Pro',monospace" # Optional, Override logo font.