name = "Serverless Academy Blog"
license = "Apache-2.0"
licenselink = "https://github.com/linuxacademy/serverless-blog-theme/blob/master/LICENSE.md"
description = "Serverless Academy Blog is a theme for hugo."
tags = ["blog"]
features = ["blog"]
min_version = 0.15

[author]
    name = "Johnny Jelinek"
    homepage = "https://blog.serverlessacademy.com/"

